### ISSUE TITLE
Port to Java

### ISSUE THREAD

**Issue by kinow** [jasonpriem/HumanNameParser.php#11]
Hi, after reading about R and Node ports, and needing to use similar library in Java, here's my take on a Java port of HumanNameParser.php

https://github.com/tupilabs/HumanNameParser.java

I tried to keep the design, code, if/else's, and even tests (used testNames.txt too in the tests).

The code is ready to be deployed to Maven Central repository if there is no objection. I've added the copyright, kept the license and tried to let it clear that the code is a port of the original PHP library.

Thank you!

**Comment by kinow** [comment]
The Maven site: http://tupilabs.github.io/HumanNameParser.java/

**Comment by jasonpriem** [comment]
Awesome! Nice work!

**Comment by kinow** [comment]
Thanks @jasonpriem ! 

By the way, [we are discussing](https://issues.apache.org/jira/browse/SANDBOX-487) to use the Java code with some modifications in Apache Commons Text. 

Even though the licenses are compatible, it is preferable to use the code if your are OK with that - since you're the original author :-)

Would that be all right?

**Comment by kinow** [comment]
ping? :-)
